# .gitlab-ci.yml

# Use the .NET SDK image to build and test the application
image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

# Build stage
build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

# Test stage
test:
  stage: test
  script:
    - dotnet test
