# Use the official .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the project file(s) to the working directory
COPY *Backend.csproj ./

# Restore project dependencies
RUN dotnet restore

# Copy the entire project to the working directory
COPY . ./

# Build the application
RUN dotnet publish -c Release -o /publish

# Use the official .NET runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Set the working directory for the runtime image
WORKDIR /app

# Copy the build output from the previous stage
COPY --from=build /publish .

# Expose the port the application runs on
EXPOSE 5000
EXPOSE 5001

# Define the entry point for the container
ENTRYPOINT ["dotnet", "Backend.dll"]
