name: Publish Docker Images

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./  # Root directory as the build context
          file: ./Backend/Dockerfile  # Specify the path to the Dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-frontend:latest

      - name: Build and push FrontendUser image
        uses: docker/build-push-action@v5
        with:
          context: ./FrontendUser
          file: dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-frontenduser:latest
