name: Publish Docker Images

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 3: Build and push Backend image
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend/Dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-backend:latest

      # Step 4: Build and push Frontend image
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Frontend/Dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-frontend:latest

      # Step 5: Build and push FrontendUser image
      - name: Build and push FrontendUser image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: FrontendUser/Dockerfile
          push: true
          tags: stefhoek/s3-dbo2t-frontenduser:latest
