name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Run UnitTests
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: |
          cd backend/testproject
          dotnet restore

      - name: Run Unit Tests
        run: |
          cd backend/testproject
          dotnet test TestProject.csproj --logger:trx --results-directory:./test-results

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: backend/testproject/test-results
          
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: Frontend

      - name: Install dependencies
        run: npm install
        working-directory: FrontendUser

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: Frontend

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: FrontendUser

  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run collection.json
        working-directory: Backend
